services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8880:80"
    depends_on:
      - db
    links:
      - db:mysql
    networks:
      - my_network

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: atshop_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./app/atshop_db.sql:/docker-entrypoint-initdb.d/atshop_db.sql
      - my_volume:/var/lib/mysql
    networks:
      - my_network

volumes:
  my_volume:

networks:
  my_network:
